# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Koen Holzapfel's Blog
email: info@koenholzapfel.nl
description: > # this means to ignore newlines until "baseurl:"
Koen Holzapfel's blog about software engineering and related subjects.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://koenholzapfel.nl" # the base hostname & protocol for your site
github_username: kjholzapfel

# Build settings
markdown: kramdown
